### PR TITLE
Update to IdentityServer4

### PR DESCRIPTION
**Pull request by giggio**
This is what I did:
- Updated to work with IS4.
- Updated names from IS3 to IS4
- Updated dependencies (Json.net, etc)
- Changed version from 0.9 to 0.1 (new pkg, new versioning)
- Added .NET Core to the list of supported frameworks.

I have tested it on another project that was already using IS3 and `TwentyTwenty.IdentityServer3.EntityFramework7` and it worked perfectly.
Unit and integration tests also pass.

### CODE REVIEW

**Comment by jarroda** [comment]
Thank you for this pull request.  Could you please sign our CLA at To get started, <a https://www.clahub.com/agreements/2020IP/TwentyTwenty.IdentityServer4.EntityFramework7.  
Thanks.

**Comment by giggio** [comment]
Done! :)

**Comment by jarroda** [comment]
Fantastic. Thanks.

**Comment by jarroda** [comment]
I published a package of this to nuget.org.  https://www.nuget.org/packages/TwentyTwenty.IdentityServer4.EntityFramework7/

**Pull request merged**
